version: '3.8'

services:
    # PHP & Laravel
    app:
        build: .
        container_name: Tracking-views-php-apache
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - redis

    # Redis
    redis:
        image: redis:alpine
        container_name: tracking-view-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
